<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MenuAsignadas</name>
   <tag></tag>
   <elementGuidId>d44ed0d9-b340-478b-9655-f7a2ab03179d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Quantico_StylingV2_wt13_block_OutSystemsUIWeb_wt29_block_wtNavigation_wt11_wtListRecords1_ctl02_wt16_wtListRecords1_ctl00_RichWidgets_wt13_block_wtMenuSubItems_wt15_wtListRecords1_ctl02_wt18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Quantico_StylingV2_wt13_block_OutSystemsUIWeb_wt29_block_wtNavigation_wt11_wtListRecords1_ctl02_wt16_wtListRecords1_ctl00_RichWidgets_wt13_block_wtMenuSubItems_wt15_wtListRecords1_ctl02_wt18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wt13_block_OutSystemsUIWeb_wt29_block_wtNavigation_wt11_wtListRecords1_ctl02_wt16_wtListRecords1_ctl00_RichWidgets_wt13_block_wtMenuSubItems_wt15_wtListRecords1_ctl02_wt18</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>13</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Menu_SubMenuItem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://unifin-tst.outsystemsenterprise.com/Quantico/AssignedTasks.aspx</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asignadas</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Quantico_StylingV2_wt13_block_OutSystemsUIWeb_wt29_block_wtNavigation_wt11_wtListRecords1_ctl02_wt16_wtListRecords1_ctl00_RichWidgets_wt13_block_wtMenuSubItems_wt15_wtListRecords1_ctl02_wt18&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Quantico_StylingV2_wt13_block_OutSystemsUIWeb_wt29_block_wtNavigation_wt11_wtListRecords1_ctl02_wt16_wtListRecords1_ctl00_RichWidgets_wt13_block_wtMenuSubItems_wt15_wtListRecords1_ctl02_wt18']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='Quantico_StylingV2_wt13_block_OutSystemsUIWeb_wt29_block_wtNavigation_wt11_wtListRecords1_ctl02_wt16_wtListRecords1_ctl00_RichWidgets_wt13_block_wtMenuSubItems_wt15_wtListRecords1']/div[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sin Asignar'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buzón de Tareas'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--- Reportes'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://unifin-tst.outsystemsenterprise.com/Quantico/AssignedTasks.aspx')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
