<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MenuBuznTareas</name>
   <tag></tag>
   <elementGuidId>dfedbd3a-51e4-42bc-aeab-b9c213f473a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.Menu_DropDownArrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Quantico_StylingV2_wt13_block_OutSystemsUIWeb_wt29_block_wtNavigation_wt11_wtListRecords1_ctl02_wt16_wtListRecords1_ctl00_RichWidgets_wt13_block_wtMenuItem']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Menu_DropDownArrow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Quantico_StylingV2_wt13_block_OutSystemsUIWeb_wt29_block_wtNavigation_wt11_wtListRecords1_ctl02_wt16_wtListRecords1_ctl00_RichWidgets_wt13_block_wtMenuItem&quot;)/span[@class=&quot;Menu_DropDownArrow&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Quantico_StylingV2_wt13_block_OutSystemsUIWeb_wt29_block_wtNavigation_wt11_wtListRecords1_ctl02_wt16_wtListRecords1_ctl00_RichWidgets_wt13_block_wtMenuItem']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/div/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
