<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ESCENARIOS_COTIZADOR_UNIFIN_MASIVO</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>86cb41a1-f96f-4757-8d92-7a63780bf9be</testSuiteGuid>
   <testCaseLink>
      <guid>7a2c65b1-9896-458a-be23-7e0a93ad326a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UNIFIN/escenarios_solicitud_unifin_masiva</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>32a74a08-a5b7-4fa3-bb4e-7acf6f334f14</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/ESCENARIOS/CLIENTES_PENDIENTES</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>32a74a08-a5b7-4fa3-bb4e-7acf6f334f14</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>nombreEscenario</value>
         <variableId>5643f834-a19b-4b91-825a-a5aa9a9d5ff4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>32a74a08-a5b7-4fa3-bb4e-7acf6f334f14</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usuario</value>
         <variableId>06250da7-400b-44bc-8ef7-ccb7a92d538d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>32a74a08-a5b7-4fa3-bb4e-7acf6f334f14</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>cliente</value>
         <variableId>2ecebfe6-07fe-4094-8487-cf29b026dfb4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
