<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BotonBusqueda</name>
   <tag></tag>
   <elementGuidId>d865ba9f-a3b6-4718-bf37-ca4ebdff57c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Content_wtLS_Content_ctl02_OutSystemsUIWeb_wt54_block_wtContent_wt35_wt2_WebPatterns_wt257_block_wtColumn6_wt25</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Content_wtLS_Content_ctl02_OutSystemsUIWeb_wt54_block_wtContent_wt35_wt2_WebPatterns_wt257_block_wtColumn6_wt25']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Content_wtLS_Content_ctl02_OutSystemsUIWeb_wt54_block_wtContent_wt35_wt2_WebPatterns_wt257_block_wtColumn6_wt25','Quantico_StylingV2_wt21$block$OutSystemsUIWeb_wt13$block$wtContent$wtMainContent$OutSystemsUIWeb_wt17$block$wtTabs_Content$wtLS_Content$ctl02$OutSystemsUIWeb_wt54$block$wtContent$wt35$wt2$WebPatterns_wt257$block$wtColumn6$wt25','','__OSVSTATE,',''); return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wt21$block$OutSystemsUIWeb_wt13$block$wtContent$wtMainContent$OutSystemsUIWeb_wt17$block$wtTabs_Content$wtLS_Content$ctl02$OutSystemsUIWeb_wt54$block$wtContent$wt35$wt2$WebPatterns_wt257$block$wtColumn6$wt25</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Buscar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Content_wtLS_Content_ctl02_OutSystemsUIWeb_wt54_block_wtContent_wt35_wt2_WebPatterns_wt257_block_wtColumn6_wt25</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>822</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button btn-primary Is_Default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Content_wtLS_Content_ctl02_OutSystemsUIWeb_wt54_block_wtContent_wt35_wt2_WebPatterns_wt257_block_wtColumn6_wt25&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Content_wtLS_Content_ctl02_OutSystemsUIWeb_wt54_block_wtContent_wt35_wt2_WebPatterns_wt257_block_wtColumn6_wt25']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Content_wtLS_Content_ctl02_OutSystemsUIWeb_wt54_block_wtContent_wt35_wt2_WebPatterns_wt257_block_wtColumn6']/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
