<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NoDisposicion</name>
   <tag></tag>
   <elementGuidId>2e70e569-e14d-4914-b3c1-6c768d287863</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Content_wtLS_Content_ctl02_OutSystemsUIWeb_wt54_block_wtContent_wt35_wt2_wtTableRecordsDisposition_ctl03_wt143</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Content_wtLS_Content_ctl02_OutSystemsUIWeb_wt54_block_wtContent_wt35_wt2_wtTableRecordsDisposition_ctl03_wt143']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Content_wtLS_Content_ctl02_OutSystemsUIWeb_wt54_block_wtContent_wt35_wt2_wtTableRecordsDisposition_ctl03_wt143</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>877</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>AssignTaskRedirect.aspx?AssignTaskId=14447&amp;IsFromUnAssignedTasks=False&amp;Token=&amp;(Not.Licensed.For.Production)=</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1178</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Content_wtLS_Content_ctl02_OutSystemsUIWeb_wt54_block_wtContent_wt35_wt2_wtTableRecordsDisposition_ctl03_wt143&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Content_wtLS_Content_ctl02_OutSystemsUIWeb_wt54_block_wtContent_wt35_wt2_wtTableRecordsDisposition_ctl03_wt143']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Content_wtLS_Content_ctl02_OutSystemsUIWeb_wt54_block_wtContent_wt35_wt2_wtTableRecordsDisposition']/tbody/tr/td[2]/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'1178')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hold'])[2]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort column by ProductLeasingOperationTypeLabel'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST KATALON XXX TEST AP TEST AM'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LEO'])[7]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1178']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'AssignTaskRedirect.aspx?AssignTaskId=14447&amp;IsFromUnAssignedTasks=False&amp;Token=&amp;(Not.Licensed.For.Production)=')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/span/table/tbody/tr/td[2]/div/a</value>
   </webElementXpaths>
</WebElementEntity>
