<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Disposicin</name>
   <tag></tag>
   <elementGuidId>3ae68c50-1588-47ff-affb-8bdef8354450</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Header_wtLS_Header_ctl02_OutSystemsUIWeb_wt20_block_wtTitle > div > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Header_wtLS_Header_ctl02_OutSystemsUIWeb_wt20_block_wtTitle']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disposición</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Header_wtLS_Header_ctl02_OutSystemsUIWeb_wt20_block_wtTitle&quot;)/div[1]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Quantico_StylingV2_wt21_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_OutSystemsUIWeb_wt17_block_wtTabs_Header_wtLS_Header_ctl02_OutSystemsUIWeb_wt20_block_wtTitle']/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Originación'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Garantías'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Disposición']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/span/div[2]/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
