<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_filtrarCliente</name>
   <tag></tag>
   <elementGuidId>8c3c859d-2f5f-4170-b791-9a26253b3089</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RichWidgets_wt37_block_wtMainContent_OutSystemsUIWeb_wt1_block_wtColumn2_wtSearchButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RichWidgets_wt37_block_wtMainContent_OutSystemsUIWeb_wt1_block_wtColumn2_wtSearchButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'RichWidgets_wt37_block_wtMainContent_OutSystemsUIWeb_wt1_block_wtColumn2_wtSearchButton','RichWidgets_wt37$block$wtMainContent$OutSystemsUIWeb_wt1$block$wtColumn2$wtSearchButton','','__OSVSTATE,',''); return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RichWidgets_wt37$block$wtMainContent$OutSystemsUIWeb_wt1$block$wtColumn2$wtSearchButton</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Buscar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RichWidgets_wt37_block_wtMainContent_OutSystemsUIWeb_wt1_block_wtColumn2_wtSearchButton</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button btn-primary ThemeGrid_Width10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RichWidgets_wt37_block_wtMainContent_OutSystemsUIWeb_wt1_block_wtColumn2_wtSearchButton&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/UNIFIN/DatosGenerales/iframe</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RichWidgets_wt37_block_wtMainContent_OutSystemsUIWeb_wt1_block_wtColumn2_wtSearchButton']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RichWidgets_wt37_block_wtMainContent_OutSystemsUIWeb_wt1_block_wtColumn2_wtContainerButton']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
