<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chkboxConPlacas</name>
   <tag></tag>
   <elementGuidId>f6cea3a0-74af-4261-9c99-87510648221d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionPlacas_Cotizador_Widget_V2_wtNegotiatorAssetPlates_Wb_block_OutSystemsUIWeb_wt12_block_wtContent_OutSystemsUIWeb_wt30_block_wtColumn1_OutSystemsUIWeb_wt29_block_wtContent_wtWithPlatesRadioButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/input[@class='radio-button SmartInput ReadOnly']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionPlacas_Cotizador_Widget_V2_wtNegotiatorAssetPlates_Wb_block$-544410201</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionPlacas_Cotizador_Widget_V2_wtNegotiatorAssetPlates_Wb_block_OutSystemsUIWeb_wt12_block_wtContent_OutSystemsUIWeb_wt30_block_wtColumn1_OutSystemsUIWeb_wt29_block_wtContent_wtWithPlatesRadioButton</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1345</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button SmartInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionPlacas_Cotizador_Widget_V2_wtNegotiatorAssetPlates_Wb_block_OutSystemsUIWeb_wt12_block_wtContent_wt3', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionPlacas_Cotizador_Widget_V2_wtNegotiatorAssetPlates_Wb_block_OutSystemsUIWeb_wt12_block_wtContent_OutSystemsUIWeb_wt30_block_wtColumn1_OutSystemsUIWeb_wt29_block_wtContent_wtWithPlatesRadioButton','Quantico_StylingV2_wtMainSection$block$OutSystemsUIWeb_wt13$block$wtContent$wtMainContent$Disposition_Widgets_wtNegotiatorSummaryTabsWidget$block$wtSectionPlacas$Cotizador_Widget_V2_wtNegotiatorAssetPlates_Wb$block$OutSystemsUIWeb_wt12$block$wtContent$OutSystemsUIWeb_wt30$block$wtColumn1$OutSystemsUIWeb_wt29$block$wtContent$wtWithPlatesRadioButton','Change','__OSVSTATE,','');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>origvalue</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionPlacas_Cotizador_Widget_V2_wtNegotiatorAssetPlates_Wb_block_OutSystemsUIWeb_wt12_block_wtContent_OutSystemsUIWeb_wt30_block_wtColumn1_OutSystemsUIWeb_wt29_block_wtContent_wtWithPlatesRadioButton&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionPlacas_Cotizador_Widget_V2_wtNegotiatorAssetPlates_Wb_block_OutSystemsUIWeb_wt12_block_wtContent_OutSystemsUIWeb_wt30_block_wtColumn1_OutSystemsUIWeb_wt29_block_wtContent_wtWithPlatesRadioButton']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionPlacas_Cotizador_Widget_V2_wtNegotiatorAssetPlates_Wb_block_OutSystemsUIWeb_wt12_block_wtContent_OutSystemsUIWeb_wt30_block_wtColumn1_OutSystemsUIWeb_wt29_block_wtContent']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/div/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionPlacas_Cotizador_Widget_V2_wtNegotiatorAssetPlates_Wb_block$-544410201' and @id = 'Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionPlacas_Cotizador_Widget_V2_wtNegotiatorAssetPlates_Wb_block_OutSystemsUIWeb_wt12_block_wtContent_OutSystemsUIWeb_wt30_block_wtColumn1_OutSystemsUIWeb_wt29_block_wtContent_wtWithPlatesRadioButton']</value>
   </webElementXpaths>
</WebElementEntity>
