<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_mxn</name>
   <tag></tag>
   <elementGuidId>11c57c76-991b-44ab-8844-ca29ba5862e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Quantico_StylingV2_wt12_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Cotizador_Widget_wtInsuranceQuoteWB_block_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt115_block_wtContent_wtAviationInsuranceForm_OutSystemsUIWeb_wt391_block_wtColumn2_OutSystemsUIWeb_wt381_block_wtContent_wtrdbMXN</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'radio' and @class = 'radio-button' and @value = '2']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[text() = 'M.N.']/parent::div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wt12_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Cotizador_Widget_wtInsuranceQuoteWB_block_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt115_block_wtContent_wtAviationInsuranceForm$1978871664</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wtrdbMXN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>238</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('Quantico_StylingV2_wt12_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Cotizador_Widget_wtInsuranceQuoteWB_block_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt115_block_wtContent_wtAviationInsuranceForm_wtbtnSave2', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Quantico_StylingV2_wt12_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Cotizador_Widget_wtInsuranceQuoteWB_block_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt115_block_wtContent_wtAviationInsuranceForm_OutSystemsUIWeb_wt391_block_wtColumn2_OutSystemsUIWeb_wt381_block_wtContent_wtrdbMXN&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Quantico_StylingV2_wt12_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Cotizador_Widget_wtInsuranceQuoteWB_block_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt115_block_wtContent_wtAviationInsuranceForm_OutSystemsUIWeb_wt391_block_wtColumn2_OutSystemsUIWeb_wt381_block_wtContent_wtrdbMXN']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Quantico_StylingV2_wt12_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Cotizador_Widget_wtInsuranceQuoteWB_block_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt115_block_wtContent_wtAviationInsuranceForm_OutSystemsUIWeb_wt391_block_wtColumn2_OutSystemsUIWeb_wt381_block_wtContent']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'Quantico_StylingV2_wt12_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Cotizador_Widget_wtInsuranceQuoteWB_block_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt115_block_wtContent_wtAviationInsuranceForm$1978871664']</value>
   </webElementXpaths>
</WebElementEntity>
