<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>switch_clientePropSeguro</name>
   <tag></tag>
   <elementGuidId>16018dd1-9440-465b-8e57-d9561bf81e17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Quantico_StylingV2_wt12_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Cotizador_Widget_wtInsuranceQuoteWB_block_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt62_block_wtContent_OutSystemsUIWeb_wt13_block_wtContent_OutSystemsUIWeb_wt105_block_wtCheckBox_wt80</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Quantico_StylingV2_wt12_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Cotizador_Widget_wtInsuranceQuoteWB_block_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt62_block_wtContent_OutSystemsUIWeb_wt13_block_wtContent_OutSystemsUIWeb_wt105_block_wtCheckBox_wt80']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wt12$block$OutSystemsUIWeb_wt13$block$wtContent$wtMainContent$Cotizador_Widget_wtInsuranceQuoteWB$block$OutSystemsUIWeb_wt38$block$wtTabs_Content$OutSystemsUIWeb_wt62$block$wtContent$OutSystemsUIWeb_wt13$block$wtContent$OutSystemsUIWeb_wt105$block$wtCheckBox$wt80</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wt12_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Cotizador_Widget_wtInsuranceQuoteWB_block_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt62_block_wtContent_OutSystemsUIWeb_wt13_block_wtContent_OutSystemsUIWeb_wt105_block_wtCheckBox_wt80</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>640</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'Quantico_StylingV2_wt12_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Cotizador_Widget_wtInsuranceQuoteWB_block_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt62_block_wtContent_OutSystemsUIWeb_wt13_block_wtContent_OutSystemsUIWeb_wt105_block_wtCheckBox_wt80','Quantico_StylingV2_wt12$block$OutSystemsUIWeb_wt13$block$wtContent$wtMainContent$Cotizador_Widget_wtInsuranceQuoteWB$block$OutSystemsUIWeb_wt38$block$wtTabs_Content$OutSystemsUIWeb_wt62$block$wtContent$OutSystemsUIWeb_wt13$block$wtContent$OutSystemsUIWeb_wt105$block$wtCheckBox$wt80','Change','__OSVSTATE,','');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Quantico_StylingV2_wt12_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Cotizador_Widget_wtInsuranceQuoteWB_block_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt62_block_wtContent_OutSystemsUIWeb_wt13_block_wtContent_OutSystemsUIWeb_wt105_block_wtCheckBox_wt80&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Quantico_StylingV2_wt12_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Cotizador_Widget_wtInsuranceQuoteWB_block_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt62_block_wtContent_OutSystemsUIWeb_wt13_block_wtContent_OutSystemsUIWeb_wt105_block_wtCheckBox_wt80']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Quantico_StylingV2_wt12_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Cotizador_Widget_wtInsuranceQuoteWB_block_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt62_block_wtContent_OutSystemsUIWeb_wt13_block_wtContent_OutSystemsUIWeb_wt105_block_wtCheckBox']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
