<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Seguros</name>
   <tag></tag>
   <elementGuidId>985b4700-f465-449c-80c7-e971aab5bee4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wt23_wtNegotiationStageList_ctl06_wt10_OutSystemsUIWeb_wt1_block_wtColumn1 > div.negotiator-tab-title-header.vertical-align > div.ThemeGrid_Width9.ThemeGrid_MarginGutter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wt23_wtNegotiationStageList_ctl06_wt10_OutSystemsUIWeb_wt1_block_wtColumn1']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ThemeGrid_Width9 ThemeGrid_MarginGutter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seguros</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wt23_wtNegotiationStageList_ctl06_wt10_OutSystemsUIWeb_wt1_block_wtColumn1&quot;)/div[@class=&quot;negotiator-tab-title-header vertical-align&quot;]/div[@class=&quot;ThemeGrid_Width9 ThemeGrid_MarginGutter&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wt23_wtNegotiationStageList_ctl06_wt10_OutSystemsUIWeb_wt1_block_wtColumn1']/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activo'])[3]/following::div[11]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condiciones Financieras'])[4]/following::div[22]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='En proceso'])[1]/preceding::div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expediente'])[1]/preceding::div[13]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seguros']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/div/div/div/div/div/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
