<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_guardar</name>
   <tag></tag>
   <elementGuidId>5d4054cf-4dc5-4a71-b147-e8fed80c7a20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_wt96</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_wt93']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if (OsPage_ClientValidate('Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_wt96')) OsAjax(arguments[0] || window.event,'Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_wt96','Quantico_StylingV2_wtMainSection$block$OutSystemsUIWeb_wt13$block$wtContent$wtMainContent$Disposition_Widgets_wtNegotiatorSummaryTabsWidget$block$wtSectionActivo$wt48$OutSystemsUIWeb_wt38$block$wtTabs_Content$OutSystemsUIWeb_wt5$block$wtContent$Cotizador_Widget_V2_wtNegotiatorAsset_Wb$block$wt96','','__OSVSTATE,',''); return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wtMainSection$block$OutSystemsUIWeb_wt13$block$wtContent$wtMainContent$Disposition_Widgets_wtNegotiatorSummaryTabsWidget$block$wtSectionActivo$wt48$OutSystemsUIWeb_wt38$block$wtTabs_Content$OutSystemsUIWeb_wt5$block$wtContent$Cotizador_Widget_V2_wtNegotiatorAsset_Wb$block$wt96</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Guardar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_wt96</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>720</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button Is_Default ThemeGrid_MarginGutter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_wt96&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_wt96']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_wtButtons']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'Quantico_StylingV2_wtMainSection$block$OutSystemsUIWeb_wt13$block$wtContent$wtMainContent$Disposition_Widgets_wtNegotiatorSummaryTabsWidget$block$wtSectionActivo$wt48$OutSystemsUIWeb_wt38$block$wtTabs_Content$OutSystemsUIWeb_wt5$block$wtContent$Cotizador_Widget_V2_wtNegotiatorAsset_Wb$block$wt96' and @id = 'Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_wt96']</value>
   </webElementXpaths>
</WebElementEntity>
