<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>colores_exterior</name>
   <tag></tag>
   <elementGuidId>b88042e9-b5a5-4061-9a7d-ea839032947f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt116_block_wtContent_wt84_wtAssetColors_Table_ctl00_wtInputExteriorColor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt114_block_wtContent_wt84_wtAssetColors_Table_ctl00_wtInputExteriorColor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wtMainSection$block$OutSystemsUIWeb_wt13$block$wtContent$wtMainContent$Disposition_Widgets_wtNegotiatorSummaryTabsWidget$block$wtSectionActivo$wt48$OutSystemsUIWeb_wt38$block$wtTabs_Content$OutSystemsUIWeb_wt5$block$wtContent$Cotizador_Widget_V2_wtNegotiatorAsset_Wb$block$OutSystemsUIWeb_wt116$block$wtContent$wt84$wtAssetColors_Table$ctl00$wtInputExteriorColor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt116_block_wtContent_wt84_wtAssetColors_Table_ctl00_wtInputExteriorColor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>440</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input OSFillParent Mandatory</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt116_block_wtContent_wt84_wt2', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt116_block_wtContent_wt84_wtAssetColors_Table_ctl00_wtInputExteriorColor&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt116_block_wtContent_wt84_wtAssetColors_Table_ctl00_wtInputExteriorColor']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt116_block_wtContent_wt84_wtAssetColors_Table_ctl00_wtOutsiteColor']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Quantico_StylingV2_wtMainSection$block$OutSystemsUIWeb_wt13$block$wtContent$wtMainContent$Disposition_Widgets_wtNegotiatorSummaryTabsWidget$block$wtSectionActivo$wt48$OutSystemsUIWeb_wt38$block$wtTabs_Content$OutSystemsUIWeb_wt5$block$wtContent$Cotizador_Widget_V2_wtNegotiatorAsset_Wb$block$OutSystemsUIWeb_wt116$block$wtContent$wt84$wtAssetColors_Table$ctl00$wtInputExteriorColor' and @type = 'text' and @id = 'Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt116_block_wtContent_wt84_wtAssetColors_Table_ctl00_wtInputExteriorColor']</value>
   </webElementXpaths>
</WebElementEntity>
