<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>monto_operacion_precio_activo</name>
   <tag></tag>
   <elementGuidId>fe2dbf1e-2da2-435b-aed5-5eebaa61e3bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt50_block_wtContent_wtNegociatorAssetAmount_OutSystemsUIWeb_wt11_block_wtColumn1_WebPatterns_wt74_block_wtColumn1_QuanticoCommon_Widget_wtTxtAssetAmount_block_wtTxtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt47_block_wtContent_wtNegociatorAssetAmount_OutSystemsUIWeb_wt11_block_wtColumn1_WebPatterns_wt74_block_wtColumn1_QuanticoCommon_Widget_wtTxtAssetAmount_block_wtTxtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wtMainSection$block$OutSystemsUIWeb_wt13$block$wtContent$wtMainContent$Disposition_Widgets_wtNegotiatorSummaryTabsWidget$block$wtSectionActivo$wt48$OutSystemsUIWeb_wt38$block$wtTabs_Content$OutSystemsUIWeb_wt5$block$wtContent$Cotizador_Widget_V2_wtNegotiatorAsset_Wb$block$OutSystemsUIWeb_wt50$block$wtContent$wtNegociatorAssetAmount$OutSystemsUIWeb_wt11$block$wtColumn1$WebPatterns_wt74$block$wtColumn1$QuanticoCommon_Widget_wtTxtAssetAmount$block$wtTxtInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>500</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt50_block_wtContent_wtNegociatorAssetAmount_OutSystemsUIWeb_wt11_block_wtColumn1_WebPatterns_wt74_block_wtColumn1_QuanticoCommon_Widget_wtTxtAssetAmount_block_wtTxtInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>705</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input OSFillParent Mandatory SmartInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onoschange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt50_block_wtContent_wtNegociatorAssetAmount_OutSystemsUIWeb_wt11_block_wtColumn1_WebPatterns_wt74_block_wtColumn1_QuanticoCommon_Widget_wtTxtAssetAmount_block_wtTxtInput','Quantico_StylingV2_wtMainSection$block$OutSystemsUIWeb_wt13$block$wtContent$wtMainContent$Disposition_Widgets_wtNegotiatorSummaryTabsWidget$block$wtSectionActivo$wt48$OutSystemsUIWeb_wt38$block$wtTabs_Content$OutSystemsUIWeb_wt5$block$wtContent$Cotizador_Widget_V2_wtNegotiatorAsset_Wb$block$OutSystemsUIWeb_wt50$block$wtContent$wtNegociatorAssetAmount$OutSystemsUIWeb_wt11$block$wtColumn1$WebPatterns_wt74$block$wtColumn1$QuanticoCommon_Widget_wtTxtAssetAmount$block$wtTxtInput','Change','__OSVSTATE,',osOnChangeTimerDelay);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OsAjaxDelayed(null,'Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt50_block_wtContent_wtNegociatorAssetAmount_OutSystemsUIWeb_wt11_block_wtColumn1_WebPatterns_wt74_block_wtColumn1_QuanticoCommon_Widget_wtTxtAssetAmount_block_wtTxtInput','Quantico_StylingV2_wtMainSection$block$OutSystemsUIWeb_wt13$block$wtContent$wtMainContent$Disposition_Widgets_wtNegotiatorSummaryTabsWidget$block$wtSectionActivo$wt48$OutSystemsUIWeb_wt38$block$wtTabs_Content$OutSystemsUIWeb_wt5$block$wtContent$Cotizador_Widget_V2_wtNegotiatorAsset_Wb$block$OutSystemsUIWeb_wt50$block$wtContent$wtNegociatorAssetAmount$OutSystemsUIWeb_wt11$block$wtColumn1$WebPatterns_wt74$block$wtColumn1$QuanticoCommon_Widget_wtTxtAssetAmount$block$wtTxtInput','Change','__OSVSTATE,',0);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>origvalue</name>
      <type>Main</type>
      <value>$ 500.00</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>$ 0.00</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt50_block_wtContent_wtNegociatorAssetAmount_OutSystemsUIWeb_wt11_block_wtColumn1_WebPatterns_wt74_block_wtColumn1_QuanticoCommon_Widget_wtTxtAssetAmount_block_wtTxtInput&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt50_block_wtContent_wtNegociatorAssetAmount_OutSystemsUIWeb_wt11_block_wtColumn1_WebPatterns_wt74_block_wtColumn1_QuanticoCommon_Widget_wtTxtAssetAmount_block_wtTxtInput']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt50_block_wtContent_wtNegociatorAssetAmount_OutSystemsUIWeb_wt11_block_wtColumn1_WebPatterns_wt74_block_wtColumn1_QuanticoCommon_Widget_wtTxtAssetAmount_block']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Quantico_StylingV2_wtMainSection$block$OutSystemsUIWeb_wt13$block$wtContent$wtMainContent$Disposition_Widgets_wtNegotiatorSummaryTabsWidget$block$wtSectionActivo$wt48$OutSystemsUIWeb_wt38$block$wtTabs_Content$OutSystemsUIWeb_wt5$block$wtContent$Cotizador_Widget_V2_wtNegotiatorAsset_Wb$block$OutSystemsUIWeb_wt50$block$wtContent$wtNegociatorAssetAmount$OutSystemsUIWeb_wt11$block$wtColumn1$WebPatterns_wt74$block$wtColumn1$QuanticoCommon_Widget_wtTxtAssetAmount$block$wtTxtInput' and @type = 'text' and @id = 'Quantico_StylingV2_wtMainSection_block_OutSystemsUIWeb_wt13_block_wtContent_wtMainContent_Disposition_Widgets_wtNegotiatorSummaryTabsWidget_block_wtSectionActivo_wt48_OutSystemsUIWeb_wt38_block_wtTabs_Content_OutSystemsUIWeb_wt5_block_wtContent_Cotizador_Widget_V2_wtNegotiatorAsset_Wb_block_OutSystemsUIWeb_wt50_block_wtContent_wtNegociatorAssetAmount_OutSystemsUIWeb_wt11_block_wtColumn1_WebPatterns_wt74_block_wtColumn1_QuanticoCommon_Widget_wtTxtAssetAmount_block_wtTxtInput' and @placeholder = '$ 0.00']</value>
   </webElementXpaths>
</WebElementEntity>
