<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_buscar</name>
   <tag></tag>
   <elementGuidId>b612a569-800e-4b4c-b00b-9dcac7684f89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RichWidgets_wt20_block_wtMainContent_OutSystemsUIWeb_wt5_block_wtColumn2_wtSearchButton']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
