<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>switch_nuevo</name>
   <tag></tag>
   <elementGuidId>0b199243-829f-4e96-b333-45c3617a9b3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Quantico_StylingV2_wt144_block_OutSystemsUIWeb_wt14_block_wtContent_wtMainContent_OutSystemsUIWeb_wt44_block_wtColumn2_wtQuoteAsset_WebBlock_WebPatterns_wtfsAsset_block_wtContent_OutSystemsUIWeb_wt71_block_wtColumn2_OutSystemsUIWeb_wt60_block_wtCheckBox_wtchkAsset_IsNew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Quantico_StylingV2_wt144_block_OutSystemsUIWeb_wt14_block_wtContent_wtMainContent_OutSystemsUIWeb_wt44_block_wtColumn2_wtQuoteAsset_WebBlock_WebPatterns_wtfsAsset_block_wtContent_OutSystemsUIWeb_wt71_block_wtColumn2_OutSystemsUIWeb_wt60_block_wtCheckBox_wtchkAsset_IsNew']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wt144$block$OutSystemsUIWeb_wt14$block$wtContent$wtMainContent$OutSystemsUIWeb_wt44$block$wtColumn2$wtQuoteAsset_WebBlock$WebPatterns_wtfsAsset$block$wtContent$OutSystemsUIWeb_wt71$block$wtColumn2$OutSystemsUIWeb_wt60$block$wtCheckBox$wtchkAsset_IsNew</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Quantico_StylingV2_wt144_block_OutSystemsUIWeb_wt14_block_wtContent_wtMainContent_OutSystemsUIWeb_wt44_block_wtColumn2_wtQuoteAsset_WebBlock_WebPatterns_wtfsAsset_block_wtContent_OutSystemsUIWeb_wt71_block_wtColumn2_OutSystemsUIWeb_wt60_block_wtCheckBox_wtchkAsset_IsNew</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>162</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox SmartInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('Quantico_StylingV2_wt144_block_OutSystemsUIWeb_wt14_block_wtContent_wtMainContent_OutSystemsUIWeb_wt44_block_wtColumn2_wtQuoteAsset_WebBlock_WebPatterns_wtfsAsset_block_wtContent_OutSystemsUIWeb_wt71_block_wtColumn2_wtRAction', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'Quantico_StylingV2_wt144_block_OutSystemsUIWeb_wt14_block_wtContent_wtMainContent_OutSystemsUIWeb_wt44_block_wtColumn2_wtQuoteAsset_WebBlock_WebPatterns_wtfsAsset_block_wtContent_OutSystemsUIWeb_wt71_block_wtColumn2_OutSystemsUIWeb_wt60_block_wtCheckBox_wtchkAsset_IsNew','Quantico_StylingV2_wt144$block$OutSystemsUIWeb_wt14$block$wtContent$wtMainContent$OutSystemsUIWeb_wt44$block$wtColumn2$wtQuoteAsset_WebBlock$WebPatterns_wtfsAsset$block$wtContent$OutSystemsUIWeb_wt71$block$wtColumn2$OutSystemsUIWeb_wt60$block$wtCheckBox$wtchkAsset_IsNew','Change','__OSVSTATE,','');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>origvalue</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Quantico_StylingV2_wt144_block_OutSystemsUIWeb_wt14_block_wtContent_wtMainContent_OutSystemsUIWeb_wt44_block_wtColumn2_wtQuoteAsset_WebBlock_WebPatterns_wtfsAsset_block_wtContent_OutSystemsUIWeb_wt71_block_wtColumn2_OutSystemsUIWeb_wt60_block_wtCheckBox_wtchkAsset_IsNew&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Quantico_StylingV2_wt144_block_OutSystemsUIWeb_wt14_block_wtContent_wtMainContent_OutSystemsUIWeb_wt44_block_wtColumn2_wtQuoteAsset_WebBlock_WebPatterns_wtfsAsset_block_wtContent_OutSystemsUIWeb_wt71_block_wtColumn2_OutSystemsUIWeb_wt60_block_wtCheckBox_wtchkAsset_IsNew']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Quantico_StylingV2_wt144_block_OutSystemsUIWeb_wt14_block_wtContent_wtMainContent_OutSystemsUIWeb_wt44_block_wtColumn2_wtQuoteAsset_WebBlock_WebPatterns_wtfsAsset_block_wtContent_OutSystemsUIWeb_wt71_block_wtColumn2_OutSystemsUIWeb_wt60_block_wtCheckBox']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
