<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_descripcion</name>
   <tag></tag>
   <elementGuidId>041e78a2-64f4-493d-8486-800a7b4af98a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.choices__item.needsclick.choices__item--selectable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//label[text() = 'Descripción:']//parent::div//div)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>choices__item needsclick choices__item--selectable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>__ossli_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              -
                Remove item
              
            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OutSystemsUIWeb_wt51_block_wtMainContent_wtDataForm&quot;)/table[@class=&quot;OSFillParent&quot;]/tbody[1]/tr[1]/td[1]/div[1]/div[@class=&quot;margin-bottom-s&quot;]/div[@class=&quot;choices ThemeGrid_Width11 SmartInput ReadOnly undefined&quot;]/div[@class=&quot;choices__inner&quot;]/div[@class=&quot;choices__list choices__list--single&quot;]/div[@class=&quot;choices__item needsclick choices__item--selectable&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/COTIZADOR_SEGURO/DatosActivo/iframe_1</value>
   </webElementProperties>
</WebElementEntity>
